### ISSUE TITLE
redis configuration need to be updatable

### ISSUE THREAD

**Issue by Agi-dev** [itiqiti/common#42]
into vendor/itiqiti/common/src/Itq/Bundle/ItqBundle/Resources/config/services.yml :

actual :
```yaml
# others

  app.redis:
    class: Redis
    calls:
      - ['connect', ['127.0.1.1']]
```
proposal:
```yaml
# others

  app.redis:
    class: Redis
    calls:
      - ['connect', ['%redis_name%']]
```
